<?php

use Illuminate\Database\Seeder;

class CoresultTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('coresults')->truncate();
        
        $coresults = [
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_0','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_1','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_2','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_3','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_4','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_5','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_6','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_7','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_8','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_9','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_10','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_11','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_12','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_13','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_14','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_15','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_16','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_17','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_18','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_19','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_20','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_21','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_22','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_23','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_24','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_25','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_26','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_27','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_28','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_29','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_30','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_31','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_32','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_33','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_34','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_35','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_36','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_37','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_38','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_39','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_40','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_41','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_42','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_43','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_44','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_45','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_46','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_47','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_48','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_49','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_50','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_51','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_52','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_53','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_54','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_55','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_56','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_57','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_58','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1000_59','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_0','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_1','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_2','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_3','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_4','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_5','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_6','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_7','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_8','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_9','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_10','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_11','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_12','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_13','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_14','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_15','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_16','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_17','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_18','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_19','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_20','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_21','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_22','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_23','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_24','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_25','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_26','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_27','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_28','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_29','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_30','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_31','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_32','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_33','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_34','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_35','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_36','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_37','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_38','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_39','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_40','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_41','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_42','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_43','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_44','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_45','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_46','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_47','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_48','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_49','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_50','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_51','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_52','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_53','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_54','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_55','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_56','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_57','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_58','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1002_59','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
  ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_0','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_1','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_2','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_3','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_4','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_5','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_6','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_7','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_8','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_9','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_10','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_11','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_12','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_13','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_14','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_15','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_16','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_17','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_18','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_19','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_20','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_21','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_22','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_23','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_24','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_25','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_26','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_27','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_28','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_29','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_30','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_31','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_32','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_33','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_34','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_35','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_36','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_37','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_38','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_39','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_40','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_41','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_42','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_43','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_44','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_45','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_46','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_47','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_48','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_49','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_50','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_51','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_52','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_53','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_54','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_55','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_56','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_57','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_58','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo'],
 ['item_id'=>'3','corrector_id'=>'1','mediafilename'=>'1003_59','mediafolder' =>'CORRDIM01','precorrection'=>'_','results'=>'_','state'=>'todo']
        ];

     DB::table('coresults')->insert($coresults);
    }
}
